name: Main workflow
on: [push]
jobs:
  build:
    name: Install, Test, Snapshot, e2e and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Setup puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg --no-install-recommends 
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get -y install procps google-chrome-unstable --no-install-recommends

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install

      - name: Test
        run: yarn ci

      - name: Snapshot UI
        run: yarn snapshot-ui
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: End to End
        run: yarn e2e

      - name: Deploy
        run: yarn deploy
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
